### ISSUE TITLE
Wrong code in Mux.cpp

### ISSUE THREAD

**Issue by LeFish1** [mikedotalmond/Arduino-Mux-CD74HC4067#5]
This portion:
`Mux::Mux(int dPin0, int dPin1, int dPin2, int dPin3, int signalPin, int enablePin) {
	setup(dPin0,dPin0,dPin0,dPin0,signalPin,enablePin);`

Should be
`Mux::Mux(int dPin0, int dPin1, int dPin2, int dPin3, int signalPin, int enablePin) {
	setup(dPin0,dPin1,dPin2,dPin3,signalPin,enablePin);`

**Comment by mikedotalmond** [comment]
Nice spot - thanks.
Should be fixed by d79e213ce628b64c49153b0d716939727d3affd7
